//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Mst
    {
        public int o_id { get; set; }
        public Nullable<decimal> u_id { get; set; }
        public Nullable<decimal> p_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> total { get; set; }
        public bool isprocessed { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<decimal> contact { get; set; }
        public string place { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserMst UserMst { get; set; }
    }
}
