//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopingEntities1 : DbContext
    {
        public ShopingEntities1()
            : base("name=ShopingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminMst> AdminMsts { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<Order_Mst> Order_Mst { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<UserMst> UserMsts { get; set; }
    
        public virtual ObjectResult<allproduct_Result> allproduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<allproduct_Result>("allproduct");
        }
    
        public virtual ObjectResult<contact_sp_Result> contact_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<contact_sp_Result>("contact_sp");
        }
    
        public virtual ObjectResult<discount_sp_Result> discount_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<discount_sp_Result>("discount_sp");
        }
    
        public virtual ObjectResult<history_sp_Result> history_sp(Nullable<decimal> u_id)
        {
            var u_idParameter = u_id.HasValue ?
                new ObjectParameter("u_id", u_id) :
                new ObjectParameter("u_id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<history_sp_Result>("history_sp", u_idParameter);
        }
    
        public virtual int insert_contact(string name, string email, Nullable<decimal> phn, string sub, string meg)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phnParameter = phn.HasValue ?
                new ObjectParameter("phn", phn) :
                new ObjectParameter("phn", typeof(decimal));
    
            var subParameter = sub != null ?
                new ObjectParameter("sub", sub) :
                new ObjectParameter("sub", typeof(string));
    
            var megParameter = meg != null ?
                new ObjectParameter("meg", meg) :
                new ObjectParameter("meg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_contact", nameParameter, emailParameter, phnParameter, subParameter, megParameter);
        }
    
        public virtual int insert_product(string p_nm, string img, Nullable<decimal> qt, Nullable<decimal> prc, Nullable<decimal> disc, Nullable<bool> isdis, Nullable<bool> isactv, Nullable<bool> isdelt, Nullable<bool> isnew)
        {
            var p_nmParameter = p_nm != null ?
                new ObjectParameter("p_nm", p_nm) :
                new ObjectParameter("p_nm", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var qtParameter = qt.HasValue ?
                new ObjectParameter("qt", qt) :
                new ObjectParameter("qt", typeof(decimal));
    
            var prcParameter = prc.HasValue ?
                new ObjectParameter("prc", prc) :
                new ObjectParameter("prc", typeof(decimal));
    
            var discParameter = disc.HasValue ?
                new ObjectParameter("disc", disc) :
                new ObjectParameter("disc", typeof(decimal));
    
            var isdisParameter = isdis.HasValue ?
                new ObjectParameter("isdis", isdis) :
                new ObjectParameter("isdis", typeof(bool));
    
            var isactvParameter = isactv.HasValue ?
                new ObjectParameter("isactv", isactv) :
                new ObjectParameter("isactv", typeof(bool));
    
            var isdeltParameter = isdelt.HasValue ?
                new ObjectParameter("isdelt", isdelt) :
                new ObjectParameter("isdelt", typeof(bool));
    
            var isnewParameter = isnew.HasValue ?
                new ObjectParameter("isnew", isnew) :
                new ObjectParameter("isnew", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_product", p_nmParameter, imgParameter, qtParameter, prcParameter, discParameter, isdisParameter, isactvParameter, isdeltParameter, isnewParameter);
        }
    
        public virtual int insertProduct_sp(Nullable<decimal> u_id, Nullable<decimal> p_id, Nullable<decimal> qty, Nullable<decimal> total, Nullable<decimal> contact, string plce)
        {
            var u_idParameter = u_id.HasValue ?
                new ObjectParameter("u_id", u_id) :
                new ObjectParameter("u_id", typeof(decimal));
    
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(decimal));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var contactParameter = contact.HasValue ?
                new ObjectParameter("contact", contact) :
                new ObjectParameter("contact", typeof(decimal));
    
            var plceParameter = plce != null ?
                new ObjectParameter("plce", plce) :
                new ObjectParameter("plce", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertProduct_sp", u_idParameter, p_idParameter, qtyParameter, totalParameter, contactParameter, plceParameter);
        }
    
        public virtual ObjectResult<itemselected_sp_Result> itemselected_sp(Nullable<int> pr_id)
        {
            var pr_idParameter = pr_id.HasValue ?
                new ObjectParameter("pr_id", pr_id) :
                new ObjectParameter("pr_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<itemselected_sp_Result>("itemselected_sp", pr_idParameter);
        }
    
        public virtual ObjectResult<manage_order__Result> manage_order_(Nullable<decimal> oid)
        {
            var oidParameter = oid.HasValue ?
                new ObjectParameter("oid", oid) :
                new ObjectParameter("oid", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_order__Result>("manage_order_", oidParameter);
        }
    
        public virtual ObjectResult<newproduct_sp_Result> newproduct_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<newproduct_sp_Result>("newproduct_sp");
        }
    
        public virtual int order_insert(Nullable<decimal> u_id, Nullable<decimal> p_id, Nullable<decimal> qty, Nullable<decimal> total, Nullable<decimal> contact, string plce)
        {
            var u_idParameter = u_id.HasValue ?
                new ObjectParameter("u_id", u_id) :
                new ObjectParameter("u_id", typeof(decimal));
    
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(decimal));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var contactParameter = contact.HasValue ?
                new ObjectParameter("contact", contact) :
                new ObjectParameter("contact", typeof(decimal));
    
            var plceParameter = plce != null ?
                new ObjectParameter("plce", plce) :
                new ObjectParameter("plce", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("order_insert", u_idParameter, p_idParameter, qtyParameter, totalParameter, contactParameter, plceParameter);
        }
    
        public virtual int Register_sp(string uname, string email, string pass, string add, Nullable<System.DateTime> db, Nullable<decimal> cont)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var dbParameter = db.HasValue ?
                new ObjectParameter("db", db) :
                new ObjectParameter("db", typeof(System.DateTime));
    
            var contParameter = cont.HasValue ?
                new ObjectParameter("cont", cont) :
                new ObjectParameter("cont", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Register_sp", unameParameter, emailParameter, passParameter, addParameter, dbParameter, contParameter);
        }
    
        public virtual ObjectResult<show_order_sp_Result> show_order_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<show_order_sp_Result>("show_order_sp");
        }
    
        public virtual int update_product(Nullable<decimal> p_id, string p_nm, string img, Nullable<decimal> qt, Nullable<decimal> prc, Nullable<decimal> disc, Nullable<bool> isdis, Nullable<bool> isactv, Nullable<bool> isdelt, Nullable<bool> isnew)
        {
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(decimal));
    
            var p_nmParameter = p_nm != null ?
                new ObjectParameter("p_nm", p_nm) :
                new ObjectParameter("p_nm", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var qtParameter = qt.HasValue ?
                new ObjectParameter("qt", qt) :
                new ObjectParameter("qt", typeof(decimal));
    
            var prcParameter = prc.HasValue ?
                new ObjectParameter("prc", prc) :
                new ObjectParameter("prc", typeof(decimal));
    
            var discParameter = disc.HasValue ?
                new ObjectParameter("disc", disc) :
                new ObjectParameter("disc", typeof(decimal));
    
            var isdisParameter = isdis.HasValue ?
                new ObjectParameter("isdis", isdis) :
                new ObjectParameter("isdis", typeof(bool));
    
            var isactvParameter = isactv.HasValue ?
                new ObjectParameter("isactv", isactv) :
                new ObjectParameter("isactv", typeof(bool));
    
            var isdeltParameter = isdelt.HasValue ?
                new ObjectParameter("isdelt", isdelt) :
                new ObjectParameter("isdelt", typeof(bool));
    
            var isnewParameter = isnew.HasValue ?
                new ObjectParameter("isnew", isnew) :
                new ObjectParameter("isnew", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_product", p_idParameter, p_nmParameter, imgParameter, qtParameter, prcParameter, discParameter, isdisParameter, isactvParameter, isdeltParameter, isnewParameter);
        }
    
        public virtual int updateorder_sp(Nullable<decimal> oid, Nullable<bool> process)
        {
            var oidParameter = oid.HasValue ?
                new ObjectParameter("oid", oid) :
                new ObjectParameter("oid", typeof(decimal));
    
            var processParameter = process.HasValue ?
                new ObjectParameter("process", process) :
                new ObjectParameter("process", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateorder_sp", oidParameter, processParameter);
        }
    
        public virtual int updateQt(Nullable<decimal> qty, Nullable<decimal> pid)
        {
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(decimal));
    
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateQt", qtyParameter, pidParameter);
        }
    
        public virtual ObjectResult<string> userlist(string emailid, string pass)
        {
            var emailidParameter = emailid != null ?
                new ObjectParameter("emailid", emailid) :
                new ObjectParameter("emailid", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("userlist", emailidParameter, passParameter);
        }
    }
}
